### ISSUE TITLE
wp__blc_instances doesn't exist

### ISSUE THREAD

**Issue by grzegorz-janoszka** [HongPong/broken-link-checker#36]
Hi,
I am using the latest version from github. Recently I have received a following email from cron:

Error Table 'mysite.wp__blc_instances' doesn't exist bazy danych WordPressa podczas wykonywania zapytania SELECT instance_id FROM `wp__blc_instances` WHERE container_id = 18154 AND container_type = 'post' wysłanego przez do_action_ref_array('wp_scheduled_auto_draft_delete'), WP_Hook->do_action, WP_Hook->apply_filters, wp_delete_auto_drafts, wp_delete_post, do_action('delete_post'), WP_Hook->do_action, WP_Hook->apply_filters, blcPostTypeOverlord->post_deleted

It hasn't appear even once with the "old" version.

**Comment by HongPong** [comment]
That's unusual since there were no changes to the configuration of database
tables.

My guess is that it could be an encoding issue if there are any special
characters on the table names (I'm not fluent enough to interpret the
message better). Obviously if the table is present then something is
seriously mixed up.

**Comment by grzegorz-janoszka** [comment]
The interesting thing is the double underscore between wp and blc_instances. But well, it didn't appear again and since you have you haven't changed anything DB related, then maybe it was just a glitch caused by a cosmic radiation or whatever.

Do you have any plans to include cookies support to BLC?

**Comment by HongPong** [comment]
If someone writes a cookie support on this and it can be suitably tested automatically I would definitely include it as a PR. I don't have the latitude to come up with that myself (heck I don't have a situation where I could apply it successfully, on hand).

**Comment by grzegorz-janoszka** [comment]
Just add a few links like:
http://physrev.physiology.org/content/81/3/1031.full
http://www.fasebj.org/content/25/1_Supplement/528.2
https://www.nature.com/articles/pr201551

There is also a problem (but a different one) with tracking links like that:
https://www.huffpost.com/entry/unlocking-the-sleep-gut-connection_n_8941314

**Comment by grzegorz-janoszka** [comment]
Actually the problem I reported initially has been reported by someone else as well:
https://wordpress.org/support/topic/wrong-table-name-_blc_instances/ :)
This URL contains a fix.

**Comment by HongPong** [comment]
excellent catch i would roll in a PR for sure

looks like this one too

https://wordpress.org/support/topic/extra-underscore-in-select-statement/
