### ISSUE TITLE
please help me 

### ISSUE THREAD

**Issue by suwaih** [HongPong/broken-link-checker#40]
خطأ Table 'newsliby_wp.wp__blc_instances' doesn't exist في قاعدة بيانات ووردبريس  للاستعلام SELECT instance_id FROM `wp__blc_instances` WHERE container_id = 7087 AND container_type = 'post' القادم من do_action_ref_array('wp_scheduled_auto_draft_delete'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, wp_delete_auto_drafts, wp_delete_post, do_action('delete_post'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, blcPostTypeOverlord->post_deleted

**Comment by HongPong** [comment]
hello @suwaih this issue has been addressed in a pull request and if you apply the code on the current version it should be ok now. 

https://github.com/HongPong/broken-link-checker/commit/546b6488070ef5529531bb5151bd52105d56f093

https://github.com/HongPong/broken-link-checker/commit/22f7589b7335c5a94349ba8ff3883695632edcc6
