### ISSUE TITLE
question regarding version vs. official version

### ISSUE THREAD

**Issue by atomGit** [HongPong/broken-link-checker#42]
i went to install the latest version from this repo but i see in WP that i have 1.11.8 installed and this repo is 1.11.7, yet the code here was updated after .8

can someone help me understand?

**Comment by HongPong** [comment]
@atomGit hi, this is not packaged with the version number currently. It's a fork, not a continuation, so really the old numbers don't apply. (and from my view it seems like it doesn't make sense to simply increment the number. maybe something like 1.11.8-fork-1 makes more sense?)

Earlier I had proposed potentially submitting this as a different plugin altogether later this year, but that would entail changing more of the code.

In any case the company managing the plugin has not posted any updates. I am aiming to look and see what other patches people have made on other forks but haven't done so yet - been tied up on other projects.

**Comment by atomGit** [comment]
thanks for clearing that up

and thanks again for maintaining the project

i assume the youtube API key has not been updated in your code from what i understand? that's fine, i can do that manually

**Comment by HongPong** [comment]
I have not gone into the YouTube stuff but if you have found a workable
patch a PR would be welcome, thanks :)
